import argparse
import sys
from pathlib import Path

from png2sprites.core import SpriteError, convert_file, _cn


def _colour(s: str) -> int:
    v = int(s, 0)
    if not 0 <= v <= 15:
        raise argparse.ArgumentTypeError("colour index must be 0-15")
    return v


def main(argv=None) -> int:
    p = argparse.ArgumentParser(
        prog="png2sprites",
        description="Convert a PNG sprite sheet to C64 sprite data: 64 bytes per sprite "
                    "(63 data + 1 pad), row-major cell order. Transparent = alpha 0.")
    p.add_argument("png")
    p.add_argument("-o", "--output", required=True, help="sprite data .bin")
    p.add_argument("-m", "--mode", choices=["hires", "multicolour"], default="hires",
                   help="hires: 24x21 cells, 1 colour. multicolour: 12x21 cells, 3 colours")
    p.add_argument("--mc1", type=_colour, help="shared multicolour 1 (%%01), index 0-15; default: inferred")
    p.add_argument("--mc2", type=_colour, help="shared multicolour 2 (%%11), index 0-15; default: inferred")
    p.add_argument("--colors", metavar="FILE", help="also write one byte per sprite: its $D027+ colour")
    p.add_argument("--inc", metavar="FILE", help="also write a KickAssembler include with "
                   "PREFIX_COUNT / _MC1 / _MC2 constants")
    p.add_argument("--prefix", default="SPR", help="constant prefix for --inc (default SPR)")
    a = p.parse_args(argv)
    try:
        r = convert_file(a.png, a.mode, a.mc1, a.mc2)
    except SpriteError as e:
        print(f"png2sprites: error: {e}", file=sys.stderr)
        return 1
    Path(a.output).parent.mkdir(parents=True, exist_ok=True)
    Path(a.output).write_bytes(r.data)
    if a.colors:
        Path(a.colors).write_bytes(bytes(r.colours))
    if a.inc:
        lines = [f"// generated by png2sprites from {Path(a.png).name}: do not edit",
                 f".const {a.prefix}_COUNT = {r.count}"]
        if r.mc1 is not None:
            lines += [f".const {a.prefix}_MC1 = {r.mc1}", f".const {a.prefix}_MC2 = {r.mc2}"]
        Path(a.inc).write_text("\n".join(lines) + "\n")
    extra = f", mc1={_cn(r.mc1)} mc2={_cn(r.mc2)}" if r.mc1 is not None else ""
    print(f"png2sprites: {a.png}: {r.count} {r.mode} sprites -> {a.output} "
          f"({len(r.data)} bytes){extra}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
